min_angle = -1.5
max_angle = 0.2
angle_delta = 1.5
min_speed = 100.0
max_speed = 600.0
speed_delta = 500.0
gravity = 98.1

rot_factor = { x = 0.002, y = 0.02 }
rot_y_clamp = 500.0
air_friction = 0.999
restitution = { x = 0.6, y = 0.5 }
halting_velocity = { x = 200.0, y = 100.0 }

cannon_offset = { x = 50, y = 150 }
player_offset = { x = 50, y = 150 }
boost_meter_offset = { x = 10, y = 110 }
speed_meter_offset = { x = 20, y = 200 }
buy_meter_offset = { x = 18, y = 180 }
buy_meter_size = { w = 286, h = 20 }

tree_amount = 4
rock_amount = 1

boost_meter_speed = 100
boost_meter_penalty_area = 40
boost_meter_safe_area = 10
boost_meter_crit_area = 5
boost_penalty = { x = 0.5, y = 0.5 }
boost_crit = { x = 1.5, y = 1.1 }
boost_safe = { x = 1.1, y = 1.05 }
boost_delay = 2.0
max_boost_velocity = { x = 500, y = 500 }
static_velocity_boost = { x = 100, y = 100 }
static_velocity_boost_treshold = 400

player_collider = { x = 35, y = 135, w = 30, h = 30 }

particle_amount = 20
particle_gravity = 3
particle_force = 300
particle_vel_multiplier = { x = 0.5, y = 0.1 }
particle_life = 1
crit_particle_amount = 5
crit_particle_gravity = 2
crit_particle_force = 300
crit_particle_life = 2
topleft_particle_amount = 5
topleft_particle_gravity = 10
topleft_particle_force = 200
topleft_particle_life = 0.5
bounce_particle_amount = 4
bounce_particle_gravity = 3
bounce_particle_force = 100
bounce_particle_vel_multiplier = { x = 0.6, y = 1.5 }
bounce_particle_life = 1

buy_time = 6
buy_speed = 2

dead_wait_time = 3

screen_shake_launch = { duration = 1.0, force = 100 }
screen_shake_bounce = { duration = 0.2, force = 10 }
