min_angle = -1.5
max_angle = 0.2
angle_delta = 1.5
min_speed = 100.0
max_speed = 600.0
speed_delta = 500.0
gravity = 98.1

rot_factor = { x = 0.002, y = 0.02 }
rot_y_clamp = 500.0
air_friction = 0.999
restitution = { x = 0.6, y = 0.5 }
halting_velocity = { x = 200.0, y = 100.0 }

initial_camera = { x = 0, y = -60 }
cannon_offset = { x = 0, y = 50 }
player_offset = { x = 50, y = 0 }
boost_meter_offset = { x = -40, y = -35 }
speed_meter_offset = { x = -40, y = 155 }

tree_amount = 4
rock_amount = 1

boost_meter_speed = 100
boost_meter_penalty_area = 40
boost_meter_safe_area = 10
boost_meter_crit_area = 5
boost_penalty = { x = 0.5, y = 0.5 }
boost_crit = { x = 1.5, y = 1.1 }
boost_safe = { x = 1.1, y = 1.05 }
boost_delay = 2.0
max_boost_velocity = { x = 500, y = 500 }
static_velocity_boost = { x = 100, y = 100 }
static_velocity_boost_treshold = 400

disk_spawn_rate = 100